swiftmailer:
    transport: gmail
    host: smtp.gmail.com
    port: 465
    auth_mode: login
    username: test.fundini@gmail.com
    password: FundINI777
    encryption: ssl
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false